[programs.localnet]
h = "2nUgANsTWUnnd34Gn6S37aNk6b7gnuowsskZpZP95DLU"
harmonia="HARm9wjX7iJ1eqQCckXdd1imRFXE6PsVChVdV4PbfLc"
candy_machine = "CANHaiDd6HPK3ykgunmXFNZMrZ4KbZgEidY5US2L8CTw"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha --require ts-node/register ./tests/*.ts --timeout 300000"