[programs.localnet]
h = "2nUgANsTWUnnd34Gn6S37aNk6b7gnuowsskZpZP95DLU"
harmonia = "1wzRnd4GsUaznNivPyg6vn9tEz6QGdpwSudzP72v2Wk"
candy_machine = "27Dzu1YWYfoEoLxxQeZMq1isFpAeaUqSXrChw8cVussB"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "mocha --require ts-node/register ./tests/*.ts --timeout 300000"

